// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRCvKNo5n7KT9jPd5gRDJYMlElYQUgYCg',
    appId: '1:889400273440:web:319b144169e0312713aa45',
    messagingSenderId: '889400273440',
    projectId: 'soc-chat-app-ca57e',
    authDomain: 'soc-chat-app-ca57e.firebaseapp.com',
    databaseURL: 'https://soc-chat-app-ca57e-default-rtdb.firebaseio.com',
    storageBucket: 'soc-chat-app-ca57e.firebasestorage.app',
    measurementId: 'G-4RPEDKQMS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf2OUnFBkHgjugfsD1elUe4dQAHb3y0OQ',
    appId: '1:889400273440:android:062d33f7427a1d7013aa45',
    messagingSenderId: '889400273440',
    projectId: 'soc-chat-app-ca57e',
    databaseURL: 'https://soc-chat-app-ca57e-default-rtdb.firebaseio.com',
    storageBucket: 'soc-chat-app-ca57e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoQ15YqG-6XuDqWU9H_Z2SU0AKq03I9fM',
    appId: '1:889400273440:ios:8e86b3a7185a222613aa45',
    messagingSenderId: '889400273440',
    projectId: 'soc-chat-app-ca57e',
    databaseURL: 'https://soc-chat-app-ca57e-default-rtdb.firebaseio.com',
    storageBucket: 'soc-chat-app-ca57e.firebasestorage.app',
    iosBundleId: 'com.faroukahmed74.socchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoQ15YqG-6XuDqWU9H_Z2SU0AKq03I9fM',
    appId: '1:889400273440:ios:8e86b3a7185a222613aa45',
    messagingSenderId: '889400273440',
    projectId: 'soc-chat-app-ca57e',
    databaseURL: 'https://soc-chat-app-ca57e-default-rtdb.firebaseio.com',
    storageBucket: 'soc-chat-app-ca57e.firebasestorage.app',
    iosBundleId: 'com.faroukahmed74.socchatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRCvKNo5n7KT9jPd5gRDJYMlElYQUgYCg',
    appId: '1:889400273440:web:1985b5ebdf118e3e13aa45',
    messagingSenderId: '889400273440',
    projectId: 'soc-chat-app-ca57e',
    authDomain: 'soc-chat-app-ca57e.firebaseapp.com',
    databaseURL: 'https://soc-chat-app-ca57e-default-rtdb.firebaseio.com',
    storageBucket: 'soc-chat-app-ca57e.firebasestorage.app',
    measurementId: 'G-41NX4L27GY',
  );
}
